Repository wulukewu/atcoder-statistics, pull requests merged in 2025-05, with the labels that each got.

#25 Use requests to replace chromedriver
  README.md
  main.py
  requirements.txt
  web-page/template.html
Labels: enhancement

#33 Change Title: "Difficulty" to "Score"
  main.py
  web-page/styles.css
  web-page/template.html
Labels: good first issue

#43 feat: contest label and color badge fixed
  main.py
  web-page/script.js
  web-page/styles.css
  web-page/template-list.html
  web-page/template.html
Labels: progress
